from __future__ import annotations

# Base real migrada desde el Smart Filter estable.
# Smart Filter conserva esta semántica; SharedCode solo aporta persistencia, contrato y fechas.
DEFAULT_CATEGORIES: dict[str, dict] = {'administracion': {'title': 'administracion',
                    'description': 'Administracion, oficina, facturacion y gestion documental.',
                    'enabled': True,
                    'terms': ['administracion',
                              'administrativo',
                              'oficina',
                              'recepcion',
                              'archivo',
                              'documentacion',
                              'gestion documental',
                              'facturacion',
                              'tramite',
                              'expediente',
                              'planilla',
                              'atencion al cliente',
                              'secretaria',
                              'asistente administrativo'],
                    'exclude_terms': [],
                    'search_mode': 'Todo el contenido',
                    'target_fields': ['categoria',
                                      'categorias',
                                      'category',
                                      'categories',
                                      'area',
                                      'areas',
                                      'rubro',
                                      'sector',
                                      'perfil',
                                      'perfil laboral',
                                      'puesto',
                                      'cargo',
                                      'formacion',
                                      'educacion',
                                      'experiencia',
                                      'conocimientos',
                                      'habilidades'],
                    'discard_categories': []},
 'comercial_ventas': {'title': 'comercial_ventas',
                      'description': 'Ventas, gestion comercial, clientes y propuestas.',
                      'enabled': True,
                      'terms': ['comercial',
                                'ventas',
                                'vendedor',
                                'cliente',
                                'clientes',
                                'presupuesto',
                                'cotizacion',
                                'propuesta',
                                'negociacion',
                                'seguimiento comercial',
                                'oportunidad',
                                'lead',
                                'crm',
                                'factura proforma'],
                      'exclude_terms': [],
                      'search_mode': 'Todo el contenido',
                      'target_fields': ['categoria',
                                        'categorias',
                                        'category',
                                        'categories',
                                        'area',
                                        'areas',
                                        'rubro',
                                        'sector',
                                        'perfil',
                                        'perfil laboral',
                                        'puesto',
                                        'cargo',
                                        'formacion',
                                        'educacion',
                                        'experiencia',
                                        'conocimientos',
                                        'habilidades'],
                      'discard_categories': []},
 'soporte_tecnico': {'title': 'soporte_tecnico',
                     'description': 'Soporte tecnico, reparaciones, mantenimiento e incidencias.',
                     'enabled': True,
                     'terms': ['soporte',
                               'soporte tecnico',
                               'tecnico',
                               'reparacion',
                               'mantenimiento',
                               'incidencia',
                               'problema',
                               'falla',
                               'diagnostico',
                               'equipo',
                               'pc',
                               'notebook',
                               'impresora',
                               'hardware',
                               'software'],
                     'exclude_terms': [],
                     'search_mode': 'Todo el contenido',
                     'target_fields': ['categoria',
                                       'categorias',
                                       'category',
                                       'categories',
                                       'area',
                                       'areas',
                                       'rubro',
                                       'sector',
                                       'perfil',
                                       'perfil laboral',
                                       'puesto',
                                       'cargo',
                                       'formacion',
                                       'educacion',
                                       'experiencia',
                                       'conocimientos',
                                       'habilidades'],
                     'discard_categories': []},
 'sistemas_infraestructura': {'title': 'sistemas_infraestructura',
                              'description': 'Sistemas, redes, servidores e infraestructura IT.',
                              'enabled': True,
                              'terms': ['sistemas',
                                        'infraestructura',
                                        'servidor',
                                        'red',
                                        'redes',
                                        'dominio',
                                        'active directory',
                                        'backup',
                                        'firewall',
                                        'vpn',
                                        'dns',
                                        'dhcp',
                                        'switch',
                                        'router',
                                        'ip',
                                        'usuario',
                                        'permisos'],
                              'exclude_terms': [],
                              'search_mode': 'Todo el contenido',
                              'target_fields': ['categoria',
                                                'categorias',
                                                'category',
                                                'categories',
                                                'area',
                                                'areas',
                                                'rubro',
                                                'sector',
                                                'perfil',
                                                'perfil laboral',
                                                'puesto',
                                                'cargo',
                                                'formacion',
                                                'educacion',
                                                'experiencia',
                                                'conocimientos',
                                                'habilidades'],
                              'discard_categories': []},
 'contabilidad_finanzas': {'title': 'contabilidad_finanzas',
                           'description': 'Contabilidad, finanzas, pagos, cobranzas y documentos financieros.',
                           'enabled': True,
                           'terms': ['contabilidad',
                                     'finanzas',
                                     'factura',
                                     'pago',
                                     'pagos',
                                     'cobranza',
                                     'cobranzas',
                                     'recibo',
                                     'balance',
                                     'deuda',
                                     'credito',
                                     'debito',
                                     'liquidacion',
                                     'estado de cuenta',
                                     'cuenta corriente'],
                           'exclude_terms': [],
                           'search_mode': 'Todo el contenido',
                           'target_fields': ['categoria',
                                             'categorias',
                                             'category',
                                             'categories',
                                             'area',
                                             'areas',
                                             'rubro',
                                             'sector',
                                             'perfil',
                                             'perfil laboral',
                                             'puesto',
                                             'cargo',
                                             'formacion',
                                             'educacion',
                                             'experiencia',
                                             'conocimientos',
                                             'habilidades'],
                           'discard_categories': []},
 'recursos_humanos': {'title': 'recursos_humanos',
                      'description': 'Recursos humanos, seleccion, personal y gestion interna.',
                      'enabled': True,
                      'terms': ['rrhh',
                                'recursos humanos',
                                'personal',
                                'empleado',
                                'empleados',
                                'seleccion',
                                'reclutamiento',
                                'entrevista',
                                'candidato',
                                'candidatos',
                                'legajo',
                                'licencia',
                                'ausencia',
                                'nomina',
                                'capacitacion'],
                      'exclude_terms': [],
                      'search_mode': 'Todo el contenido',
                      'target_fields': ['categoria',
                                        'categorias',
                                        'category',
                                        'categories',
                                        'area',
                                        'areas',
                                        'rubro',
                                        'sector',
                                        'perfil',
                                        'perfil laboral',
                                        'puesto',
                                        'cargo',
                                        'formacion',
                                        'educacion',
                                        'experiencia',
                                        'conocimientos',
                                        'habilidades'],
                      'discard_categories': []},
 'compras_proveedores': {'title': 'compras_proveedores',
                         'description': 'Compras, proveedores, stock, pedidos e insumos.',
                         'enabled': True,
                         'terms': ['compras',
                                   'compra',
                                   'proveedor',
                                   'proveedores',
                                   'pedido',
                                   'orden de compra',
                                   'stock',
                                   'inventario',
                                   'insumo',
                                   'insumos',
                                   'reposicion',
                                   'precio',
                                   'lista de precios',
                                   'presupuesto proveedor'],
                         'exclude_terms': [],
                         'search_mode': 'Todo el contenido',
                         'target_fields': ['categoria',
                                           'categorias',
                                           'category',
                                           'categories',
                                           'area',
                                           'areas',
                                           'rubro',
                                           'sector',
                                           'perfil',
                                           'perfil laboral',
                                           'puesto',
                                           'cargo',
                                           'formacion',
                                           'educacion',
                                           'experiencia',
                                           'conocimientos',
                                           'habilidades'],
                         'discard_categories': []},
 'legal_contratos': {'title': 'legal_contratos',
                     'description': 'Contratos, acuerdos, vencimientos y documentacion legal.',
                     'enabled': True,
                     'terms': ['legal',
                               'contrato',
                               'contratos',
                               'acuerdo',
                               'clausula',
                               'firma',
                               'firmado',
                               'vencimiento',
                               'renovacion',
                               'documento legal',
                               'terminos',
                               'condiciones',
                               'anexo',
                               'responsabilidad'],
                     'exclude_terms': [],
                     'discard_categories': [],
                     'search_mode': 'Todo el contenido',
                     'target_fields': ['categoria',
                                       'categorias',
                                       'category',
                                       'categories',
                                       'area',
                                       'areas',
                                       'rubro',
                                       'sector',
                                       'perfil',
                                       'perfil laboral',
                                       'puesto',
                                       'cargo',
                                       'formacion',
                                       'educacion',
                                       'experiencia',
                                       'conocimientos',
                                       'habilidades']},
 'logistica_operaciones': {'title': 'logistica_operaciones',
                           'description': 'Logistica, operaciones, entregas, retiros y coordinacion.',
                           'enabled': True,
                           'terms': ['logistica',
                                     'operaciones',
                                     'operacion',
                                     'envio',
                                     'entrega',
                                     'retiro',
                                     'transporte',
                                     'deposito',
                                     'coordinacion',
                                     'agenda',
                                     'ruta',
                                     'despacho',
                                     'recepcion de mercaderia',
                                     'seguimiento'],
                           'exclude_terms': [],
                           'discard_categories': [],
                           'search_mode': 'Solo campos o secciones indicadas',
                           'target_fields': ['categoria',
                                             'categorias',
                                             'area',
                                             'areas',
                                             'rubro',
                                             'sector',
                                             'perfil',
                                             'perfil laboral',
                                             'puesto',
                                             'cargo',
                                             'formacion',
                                             'educacion',
                                             'experiencia',
                                             'conocimientos',
                                             'habilidades']},
 'urgente_incidencias': {'title': 'urgente_incidencias',
                         'description': 'Urgencias, reclamos, alertas, pendientes e incidencias criticas.',
                         'enabled': True,
                         'terms': ['urgente',
                                   'prioridad',
                                   'prioritario',
                                   'incidencia',
                                   'reclamo',
                                   'alerta',
                                   'error',
                                   'critico',
                                   'pendiente',
                                   'vencido',
                                   'demorado',
                                   'bloqueado',
                                   'fallo',
                                   'falla',
                                   'emergencia'],
                         'exclude_terms': [],
                         'discard_categories': [],
                         'search_mode': 'Todo el contenido',
                         'target_fields': ['categoria',
                                           'categorias',
                                           'category',
                                           'categories',
                                           'area',
                                           'areas',
                                           'rubro',
                                           'sector',
                                           'perfil',
                                           'perfil laboral',
                                           'puesto',
                                           'cargo',
                                           'formacion',
                                           'educacion',
                                           'experiencia',
                                           'conocimientos',
                                           'habilidades']}}
